// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chqqqsmbhhxzeafpptwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocXFxc21iaGh4emVhZnBwdHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTI1NTksImV4cCI6MjA2NzYyODU1OX0.kKc8a7K8ZsEh-pge5bcSkt-K8CqN2gjMypJnpSj0oVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});